### ISSUE TITLE
Can't start on NixOS

### ISSUE THREAD

**Issue by lovesegfault** [uonai/Fortunae#1]
Hi! I've been super excited to try `fortunae`!

Tried on NixOS:
1. `nix-shell -p nodejs_latest`
2. `node --version` -> `v14.4.0`
3.
```
viins ❯ npm install

> core-js@3.6.5 postinstall /home/bemeurer/src/Fortunae/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> ejs@3.1.3 postinstall /home/bemeurer/src/Fortunae/node_modules/ejs
> node --harmony ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> electron@8.2.5 postinstall /home/bemeurer/src/Fortunae/node_modules/electron
> node install.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 488 packages from 330 contributors and audited 489 packages in 8.313s

26 packages are looking for funding
  run `npm fund` for details

found 3 vulnerabilities (2 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
```
4.
```
viins ❯ npm start

> fortunae@1.0.0 start /home/bemeurer/src/Fortunae
> electron .

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/bemeurer/src/Fortunae/node_modules/electron/dist/electron ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /home/bemeurer/src/Fortunae/node_modules/electron/dist/electron',
  path: '/home/bemeurer/src/Fortunae/node_modules/electron/dist/electron',
  spawnargs: [ '.' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fortunae@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fortunae@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bemeurer/.npm/_logs/2020-06-30T03_02_47_350Z-debug.log
```

Last but not least, the debug log:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/nix/store/8rynajqbkpv8i7b8q4izd2q7a0jgmhc2-nodejs-14.4.0/bin/node',
1 verbose cli   '/nix/store/8rynajqbkpv8i7b8q4izd2q7a0jgmhc2-nodejs-14.4.0/bin/npm',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v14.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle fortunae@1.0.0~prestart: fortunae@1.0.0
6 info lifecycle fortunae@1.0.0~start: fortunae@1.0.0
7 verbose lifecycle fortunae@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle fortunae@1.0.0~start: PATH: /nix/store/8rynajqbkpv8i7b8q4izd2q7a0jgmhc2-nodejs-14.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/bemeurer/src/Fortunae/node_modules/.bin:/home/bemeurer/.config/zsh/plugins/zsh-nix-shell/scripts:/nix/store/n46lz2amqsqlya0b6hh9c73zs590n23s-patchelf-0.11/bin:/nix/store/x45gpnpvbq0l3b933k187qh53y1fg7ll-gcc-wrapper-9.3.0/bin:/nix/store/afghxjb159hbb8g02929hhggxcpyzqbl-gcc-9.3.0/bin:/nix/store/3imnvgp2dkfpsi75ygmgksn16nksf6ls-glibc-2.30-bin/bin:/nix/store/66hc282zl28zfr8727i681vz23bqwp16-coreutils-8.31/bin:/nix/store/gx2r9xhby24ypk0n8ni3dxljm8mrka53-binutils-wrapper-2.31.1/bin:/nix/store/ydk00ssq4fyx78rpmdmq1hcmz0iw575f-binutils-2.31.1/bin:/nix/store/8rynajqbkpv8i7b8q4izd2q7a0jgmhc2-nodejs-14.4.0/bin:/nix/store/p8s52vp09jb4656w7ky8ihyfs45zrzpd-findutils-4.7.0/bin:/nix/store/zhn1r97qrwwp64z64w3ql8mbkrhlilld-diffutils-3.7/bin:/nix/store/107xlqzpnr6zqi0kpw94lia5sf78z9i8-gnused-4.8/bin:/nix/store/sb3jw7cl7x08lmbwypnvlg75mfwh175h-gnugrep-3.4/bin:/nix/store/49jh0yxh89p8w463ikkfx8wd5pw60vvz-gawk-5.1.0/bin:/nix/store/fp7nw2jra73nzwdz4bkh0kj4zlbvsik0-gnutar-1.32/bin:/nix/store/sxkxa185n1b1l0yhsjr9g9xhaxd3mf3n-gzip-1.10/bin:/nix/store/f5qx5f9cnk8wbgdgzr4cslz93r7sazfm-bzip2-1.0.6.0.1-bin/bin:/nix/store/i3fg9ykahhwi36jmxj6b6v42i30fhvrg-gnumake-4.2.1/bin:/nix/store/ypag3bh7y7i15xf24zihr343wi6x5i6g-bash-4.4-p23/bin:/nix/store/nyw9y987ysr6arlw6j3sjdrwf1vbsr7x-patch-2.7.6/bin:/nix/store/yahwjmq3yxmwyjzlnakafwvzggm70xy0-xz-5.2.5-bin/bin:/nix/store/9kbxhzlyn6vhrjxzfpijdfg0clz5lb1i-swaybg-1.0/bin:/run/wrappers/bin:/home/bemeurer/.nix-profile/bin:/etc/profiles/per-user/bemeurer/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/home/bemeurer/.config/zsh/plugins/zsh-vim-mode:/home/bemeurer/.config/zsh/plugins/fast-syntax-highlighting:/home/bemeurer/.config/zsh/plugins/history-search-multi-word:/home/bemeurer/.config/zsh/plugins/zsh-autopair:/home/bemeurer/.config/zsh/plugins/zsh-nix-shell:/home/bemeurer/.config/zsh/plugins/zsh-history-substring-search
9 verbose lifecycle fortunae@1.0.0~start: CWD: /home/bemeurer/src/Fortunae
10 silly lifecycle fortunae@1.0.0~start: Args: [ '-c', 'electron .' ]
11 silly lifecycle fortunae@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle fortunae@1.0.0~start: Failed to exec start script
13 verbose stack Error: fortunae@1.0.0 start: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/nix/store/8rynajqbkpv8i7b8q4izd2q7a0jgmhc2-nodejs-14.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/nix/store/8rynajqbkpv8i7b8q4izd2q7a0jgmhc2-nodejs-14.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid fortunae@1.0.0
15 verbose cwd /home/bemeurer/src/Fortunae
16 verbose Linux 5.4.47
17 verbose argv "/nix/store/8rynajqbkpv8i7b8q4izd2q7a0jgmhc2-nodejs-14.4.0/bin/node" "/nix/store/8rynajqbkpv8i7b8q4izd2q7a0jgmhc2-nodejs-14.4.0/bin/npm" "start"
18 verbose node v14.4.0
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error fortunae@1.0.0 start: `electron .`
22 error Exit status 1
23 error Failed at the fortunae@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Cheers!

**Comment by uonai** [comment]
Thanks for submitting this issue, still working on the Linux build. I do have it working on Ubuntu but I'll see what I can do here.
